# Generated by Django 2.2.5 on 2019-10-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen_perfil',
            field=models.TextField(default='/Users/ianMJ/Documents/ESCOM/tt/SuperTT/supertt/media/imgUsuario/avatarDefault.png'),
        ),
    ]
