# Generated by Django 2.2.5 on 2019-10-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191018_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estudios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Estudios'),
        ),
    ]
