# Generated by Django 2.2.5 on 2019-10-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Traduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('archivo', models.TextField()),
                ('traduccion', models.TextField()),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.Proyecto')),
            ],
        ),
    ]
