# Generated by Django 2.2.5 on 2019-10-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20191002_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccion',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
