# Generated by Django 2.2.5 on 2019-10-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20191020_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traduccion',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
