# Generated by Django 2.2.5 on 2019-10-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20191021_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traduccion',
            name='archivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='traduccion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='traduccion',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='traduccion',
            name='traduccion',
            field=models.TextField(blank=True),
        ),
    ]
