# Generated by Django 2.2.6 on 2019-10-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20191027_2325'),
        ('proyectos', '0006_auto_20191028_0516'),
    ]

    operations = [
    ]
