# Generated by Django 2.2.5 on 2019-10-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_merge_20191028_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
