# Generated by Django 3.0.5 on 2020-05-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20191030_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccion',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
    ]
